language: node_js
node_js: stable

# assign build branches
branches:
  only:
    - blog-source

before_install:
  - openssl aes-256-cbc -K $encrypted_a0b7f0848317_key -iv $encrypted_a0b7f0848317_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - npm install -g hexo-cli # 安装 hexo
  - git clone -b mod https://github.com/quentin-chen/hexo-theme-even.git themes/even

# S: Build Lifecycle
install:
  - npm install # 安装 package.json 中的插件

script:
  - hexo generate

after_success:
  - git config --global user.name "Quentin_Chen"
  - git config --global user.email "quentin.chen@foxmail.com"
  - sed -i'' "/^ *repo/s~github\.com~${githubToken}@github.com~" _config.yml
  - hexo deploy
# E: Build LifeCycle